### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by TCrosmanDSI** [JohnCampionJr/Blazor5MultipleApps#1]
First off, thank you for sharing this!

I've tried to recreate your project line by line but can't get mine to run...

My steps were:

1. Create a Blazor Wasm project
2. Check the box for Asp.Net Core Hosted
3. Then I modified all of the files to match yours.

It will run, but I get a file not found 404 error when navigate to the sites.

Any ideas?

**Comment by TCrosmanDSI** [comment]
I just found the hidden import folders, so I'm guessing it's something in there.

**Comment by ImaginaryDevelopment** [comment]
Did you get this working? I'm trying to do the same

**Comment by JohnCampionJr** [comment]
I just tried cloning the repo and it works for me.  I'm going to update to .net6 ASAP.
